[project]
name = "openbb-app"
version = "1.5.8"
description = "FinAnalyzer backend (OpenBB App)"
readme = "README.md"
authors = [
    { name = "Roger Ye", email = "shugaoye@yahoo.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mysharelib>=1.0.5",
    "openbb>=4.7.1",
    "openbb-ai>=1.8.7",
    "openbb-akshare>=1.2.1",
    "openbb-tdx>=1.2.0",
    "openbb-tushare>=1.2.0",
    "pydantic-settings>=2.14.1",
    "sse-starlette>=3.4.4",
    "uvicorn>=0.40.0",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
openbb-app = "openbb_app.main:start"
openbb-update = "openbb_app.update_equity_data:start"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipykernel>=6.30.1",
    "pytest>=9.0.2",
    "ruff>=0.15.13",
]

[tool.pyright]
reportMissingTypeStubs = false
